title: Belal Sejouk
email: b.sejouk@gmail.com
description: The Personal Site of Belal Sejouk
baseurl: "/" # the subpath of the site, e.g. /blog
url: "http://belalsejouk.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: billoosijok
github_username:  billoosijok

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  - sections

